wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/search/", views.search, name="search"),
    path("newpage", views.new_page, name="new_page"),
    path("add", views.add, name="add"),
    path("editpage/<str:title>", views.edit_page, name="edit_page"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random", views.random, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django import forms
from django.utils.safestring import mark_safe
import random as rand

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    
    if util.get_entry(title) is None:
        return HttpResponse(f"Error: Could not find a page for {title.capitalize()}!")
    else:
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "entry": util.get_entry(title)
        })

def search(request):
    form = request.GET
    search = form['q'].lower()
    print(search)
    print(util.list_entries())
    if search in (title.lower() for title in util.list_entries()):
        return entry(request, search)
    else:
        return search_results(request, search)

def search_results(request, search):
    get_items = []
    for entry in util.list_entries():
        if search in entry.lower():
            get_items.append(entry)
    return render(request, "encyclopedia/search_results.html", {
        "entries": get_items
    })

class NewPageForm(forms.Form):
    title = forms.CharField(label=mark_safe("Title"))
    content = forms.CharField(widget=forms.Textarea, label=mark_safe("Content"))

def new_page(request, title=None):
    return render(request, "encyclopedia/new_page.html", {
        "form": NewPageForm(),
        "title": title
    })

def add(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            for page in util.list_entries():
                if page.lower() == title.lower():
                    return new_page(request, title)
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return entry(request, title)
    else:
        return HttpResponse("Error")

class EditPageForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea, label=mark_safe("Content"))

def edit_page(request, title):
    return render(request, "encyclopedia/edit_page.html", {
        "form": EditPageForm({'content': util.get_entry(title)}),
        "title": title
    })

def edit(request, title):
    if request.method == "POST":
        form = EditPageForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return entry(request, title)
    else:
        return HttpResponse("Error")
    
def random(request):
    title = util.list_entries()[rand.randint(0, len(util.list_entries())-1)]
    return entry(request, title)

wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>Edit Wiki Page: {{title}}</h1>
    <form action="{% url 'encyclopedia:edit' title=title %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{% load markdown_extras %}

{% block title %}
{{title}}
{% endblock %}

{% block body %}
{{ entry | markdown | safe }}
<a href="{% url 'encyclopedia:edit_page' title=title %}">Edit</a>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>{{entry}}</li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" style="width:80%">
                    <input type="submit" value="🔍" style="width:30px; height:30px; font-size: 10px; border-width:0">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href={% url 'encyclopedia:random' %}>Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
    <h1>New Wiki Page:</h1>
    {% if title|length > 0 %}
    <p>Error: there is already a wiki page called {{title}}</p>
    {% endif %}
    <form action="{% url 'encyclopedia:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>All Results</h1>

    <ul>
        {% for entry in entries %}
        <a href="{% url 'encyclopedia:entry' title=entry %}"><li>{{entry}}</li></a>
        {% empty %}
        <p>No entries matching this search.</p>
        {% endfor %}
    </ul>

{% endblock %}